GET http://localhost:4000/user-api/users

### read user by obj id
GET http://localhost:4000/user-api/users/697dc9b634bbf9189a1641fa

###
//create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"anil",
    "password":"34627",
    "age":21

}

###
//update user by id
PUT http://localhost:4000/user-api/users/697dc9b634bbf9189a1641fa
Content-Type: application/json

{
    "username":"swamy",
    "password":"12345",
    "age":21

}

###delete user by objid
DELETE http://localhost:4000/user-api/users/697f2796a9ec3bcdc941cbbc


### read all the products
GET http://localhost:4000/product-api/products

### add a product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productname":"Nike",
    "brand":"Shoes",
    "price":2500

}

### update product by id
PUT  http://localhost:4000/product-api/products/697f2f715defc9087adb459a
Content-Type: application/json

{
    "productname":"cars",
    "brand":"maruthi",
    "price":2100

}

### delete product by id
DELETE http://localhost:4000/product-api/products/697f2f825defc9087adb459c

### read product by id
GET http://localhost:4000/product-api/products/697f2f715defc9087adb459a
